---

- name: Gather OS Specific Variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Install Common Packages
  action: >
    {{ ansible_pkg_mgr }} name="{{ item }}" state=present
  with_items: "{{ common_pkgs }}"
  become: True

- name: Configure NTP 
  template: src=ntp.conf.j2 dest=/etc/ntp.conf owner=root group=root mode=0644
  become: True
  register: ntp_conf

# http://www.serveridol.com/2011/02/14/ntp-ntpd-dead-but-subsys-locked/
- name : Configure NTPD
  lineinfile : 
    dest: '/etc/sysconfig/ntpd'
    regexp: '^OPTIONS="-u ntp:ntp -p /var/run/ntpd.pid '
    backup: yes
    state: absent
  become: True
  register: ntpd_conf

- name: Restart NTP
  service: name={{ntp_service_name}} state=restarted enabled=yes
  become: True
  when: ntp_conf.changed or ntpd_conf.changed

- name: Ensure NTP Synchronised
  shell: ntpdate -u pool.ntp.org
  register: ntpcheck
  changed_when: False
  until: ntpcheck.rc == 0
  retries: 4
  delay: 20

- name: Ensure iptables/ufw is stopped and is not running at boot time.
  service: name={{firewall_service}} state=stopped enabled=no
  when: firewall_service is defined
  become: True

- name: Disable sudo for TTY
  lineinfile: state=present create=yes dest=/etc/sudoers.d/888-dont-requiretty line="Defaults !requiretty" backup=yes
  become: True

- name: Check if selinux installed
  stat: path=/etc/selinux/config
  register: selinux_config
  become: True

- name: Ensure Selinux Disabled
  selinux: state=disabled 
  when: ansible_os_family == 'RedHat' and selinux_config.stat.exists
  become: True