---

- name: Gather OS Specific Variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ansible_distribution}}-{{ansible_distribution_version}}.yml"
        - "{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
        - "{{ansible_distribution}}.yml"
        - "{{ansible_os_family}}.yml"
        - "{{ansible_system}}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install Common Packages
  action: >
    {{ ansible_pkg_mgr }} name="{{ item }}" state=present
  with_items: "{{ common_pkgs }}"
  become: True

- name: Ensure Selinux Disabled
  selinux: state=disabled 
  when: "{{ ansible_os_family == 'Redhat' and ansible_selinux is defined and 'status' in ansible_selinux and ansible_selinux.status == 'enabled' }}"
  become: True

- name: Ensure iptables/ufw is stopped and is not running at boot time.
  service: name={{ firewall_service }} state=stopped enabled=no
  when: "{{ firewall_service is defined }}"
  become: True

- name: Disable sudo for TTY
  lineinfile: state=present create=yes dest=/etc/sudoers.d/888-dont-requiretty line="Defaults !requiretty" backup=yes
  become: True

- name: Setup NTP
  include: ntp_setup.yml
  become: True